name: GitHub Container Registry

on:
  push:
    branches:
      - main
    paths:
      - 'docker/**'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2

      - name: Get version from file
        id: vars
        run: echo ::set-output name=version::$(cat ./docker/VERSION)

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./docker/.
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/p4app:${{ steps.vars.outputs.version }}
